language: node_js
node_js:
    - "6"
    - "8"

sudo: false

services:
  - redis-server

notifications:
  irc:
    channels:
      - "irc.freenode.org#wikimedia-services"
    on_success: change
    on_failure: always

script: npm run-script coverage && (npm run-script coveralls || exit 0)
